spring:
  application:
    name: order-server
server:
  port: 8763

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    #    healthcheck:
    #      enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
esb:
  order-payment: http://localhost:8762
