spring:
  application:
    name: order-payment-demo
server:
  port: 8080

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    #    healthcheck:
    #      enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
